
-- Tutti i lidi 
SELECT Nome, Descrizione
FROM STABILIMENTO_BALNEARE;

--Il numero degli infetti in uno stabilimento
CREATE VIEW ID_PERSONE_ROSSE AS
SELECT C.ID FROM CLIENTE C 
JOIN STATO_SALUTE S 
  ON C.ID_Salute = S.ID 
WHERE S.Colore = "Rosso";

CREATE VIEW STABILIMENTO_PRENOTAZIONE_CLIENTE AS
SELECT ID_Stabilimento, ID_Prenotazione, ID_Cliente
FROM PRENOTAZIONE P
JOIN PRENOTAZIONE_POSTO P_P 
    ON P.ID = P_P.ID_Prenotazione
JOIN POSTO PO 
    ON P_P.ID_Posto = PO.ID 

SELECT COUNT(I.ID) FROM ID_PERSONE_ROSSE I 
JOIN STABILIMENTO_PRENOTAZIONE_CLIENTE SPC 
    ON SPC.ID_Cliente = I.ID 
JOIN STABILIMENTO_BALNEARE S 
    ON S.ID = SPC.ID_Stabilimento
WHERE S.Nome = "Lido Blu"; 
